kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: ruby:3.0.0
  environment:
    RAILS_ENV: test
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/test_drone_test"
    RAILS_MASTER_KEY:
      from_secret: rails_master_key
  commands:
    - bundle install
    - bundle exec rake db:create
    - bundle exec rake db:migrate
    - bundle exec rspec

services:
  - name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
